// Generated by CoffeeScript 1.7.1
var bower, clean, coffee, gulp, gutil, less, nodemon, pkg, rename;

bower = require('./bower.json');

pkg = require('./package.json');

gulp = require('gulp');

clean = require('gulp-clean');

coffee = require('gulp-coffee');

less = require('gulp-less');

nodemon = require('gulp-nodemon');

gutil = require('gulp-util');

rename = require('gulp-rename');

gulp.task('distclean', ['clean'], function() {
  return gulp.src(['node_modules', 'gulpfile.js'], {
    read: false
  }).pipe(clean());
});

gulp.task('clean', function() {
  return gulp.src(['dist'], {
    read: false
  }).pipe(clean());
});

gulp.task('coffee', function() {
  return gulp.src('src/**/*.coffee').pipe(coffee({
    bare: true
  }).on('error', gutil.log)).pipe(gulp.dest('dist'));
});

gulp.task('less', function() {
  return gulp.src('src/less/bigreg.less').pipe(rename('bigreg.min.less')).pipe(less({
    'compress': true
  })).pipe(gulp.dest('dist/web/static/' + pkg.name + '-' + pkg.version + '/css'));
});

gulp.task('nodemon', ['build'], function() {
  return nodemon({
    script: 'dist/server/app.js',
    ext: 'js',
    watch: ['dist/']
  }).on('restart', function() {
    return console.log('server restart');
  });
});

gulp.task('copy', function() {
  gulp.src('vendor/jquery/dist/**').pipe(gulp.dest('dist/web/static/jquery-' + bower.dependencies.jquery + '/js'));
  gulp.src('vendor/bootstrap/dist/**').pipe(gulp.dest('dist/web/static/bootstrap-' + bower.dependencies.bootstrap));
  gulp.src('vendor/d3/d3*.js').pipe(gulp.dest('dist/web/static/d3-' + bower.dependencies.d3 + '/js'));
  gulp.src('src/data/**').pipe(gulp.dest('dist/web/data'));
  return gulp.src('src/web/index.html').pipe(gulp.dest('dist/web'));
});

gulp.task('watch', ['build'], function() {
  gulp.watch('src/**/*', ['coffee']);
  return gulp.watch(['vendor/**', 'src/web/**'], ['copy']);
});

gulp.task('build', function() {
  return gulp.start('coffee', 'less', 'copy');
});

gulp.task('default', function() {
  return gulp.start('watch', 'nodemon');
});
